//! Cooked atmosphere header (section `0x02F06D4E`, 1800 bytes): every field, solved against all 95
//! shipped atmospheres. See docs/ATMOSPHERE_LAYOUT.md for the evidence.

pub const HEADER_SIZE: usize = 1800;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FieldKind {
    F32,
    U32,
    /// One byte; bools and small ints. Most are followed by three zero bytes.
    U8,
    Vec3,
    Vec4,
    /// 24-byte record: `u64 asset id, 8 zero bytes, u8 type + 3 pad, u32 extension hash`.
    AssetRef,
    AssetId,
    /// `u32` offset of a path string from the start of the DAT1, `0xFFFFFFFF` when unset.
    PathOffset,
}

impl FieldKind {
    pub fn size(self) -> usize {
        match self {
            Self::U8 => 1,
            Self::F32 | Self::U32 | Self::PathOffset => 4,
            Self::AssetId => 8,
            Self::Vec3 => 12,
            Self::Vec4 => 16,
            Self::AssetRef => 24,
        }
    }
}

pub struct Field {
    pub name: &'static str,
    pub offset: usize,
    pub kind: FieldKind,
}

const fn field(name: &'static str, offset: usize, kind: FieldKind) -> Field {
    Field { name, offset, kind }
}

use FieldKind::*;

/// Every non-padding field, in byte order.
pub const FIELDS: &[Field] = &[
    field("SkySettings.SkyObjects[0]", 0, PathOffset),
    field("SkySettings.SkyObjects[1]", 4, PathOffset),
    field("SkySettings.SkyObjects[2]", 8, PathOffset),
    field("SkySettings.SkyObjects[3]", 12, PathOffset),
    field("SkySettings.SkyObjects[4]", 16, PathOffset),
    field("SkySettings.SkyObjects[5]", 20, PathOffset),
    field("SkySettings.SkyObjects[6]", 24, PathOffset),
    field("SkySettings.SkyObjects[7]", 28, PathOffset),
    field("SkySettings.SkyObjectCount", 32, U32),
    field("SkySettings.SkyObjectsScale", 36, F32),
    field("SkySettings.SkyObjectsHash", 40, U32),
    field("Ocean.ReflectionMapPath", 48, PathOffset),
    field("LightGridAtmosphere", 52, PathOffset),
    field("EnvLighting.LightGridModConfig", 56, PathOffset),
    field("EnvLighting.KeylightMaterial", 60, PathOffset),
    field("SkySettings.SkyBoxCubeMap", 64, AssetRef),
    field("EnvLighting.FillLightCubeMap", 88, AssetRef),
    field("EnvLighting.KeyLightColor", 112, Vec3),
    field("EnvLighting.KeyLightIntensity", 124, F32),
    field("EnvLighting.KeyLightAzimuth", 128, F32),
    field("EnvLighting.KeyLightElevation", 132, F32),
    field("EnvLighting.SunDiskOffsetAzimuth", 136, F32),
    field("EnvLighting.SunDiskOffsetElevation", 140, F32),
    field("EnvLighting.ShadowDrawDist", 144, F32),
    field("EnvLighting.CsmLodCount", 148, U8),
    field("EnvLighting.TimeOfDay", 152, F32),
    field("EnvLighting.SunDiameter", 156, F32),
    field("EnvLighting.KeylightMaterialScale", 160, F32),
    field("EnvLighting.CasterRangeLower", 164, F32),
    field("EnvLighting.CasterRangeUpper", 168, F32),
    field("EnvLighting.FarLodCaching", 172, U8),
    field("EnvLighting.FarLodTransitionDist", 176, F32),
    field("EnvLighting.FarLodPerfModeOpts", 180, U8),
    field("EnvLighting.LightGridIntensity", 184, F32),
    field("EnvLighting.LightGridSkyMultiplier", 188, F32),
    field("EnvLighting.LightGridAORadius", 192, F32),
    field("EnvLighting.VFXLightMultiplier", 196, F32),
    field("EnvLighting.AmbientFillColor", 200, Vec3),
    field("EnvLighting.AmbientFillIntensity", 212, F32),
    field("SkySettings.SkyBoxSunThreshold", 216, F32),
    field("Weather.WetSurfaces.PorosityTexture", 224, AssetRef),
    field("Weather.WetSurfaces.StreakTexture", 248, AssetRef),
    field("Weather.WetSurfaces.SplashTexture", 272, AssetRef),
    field("Weather.WetSurfaces.Wetness", 296, F32),
    field("Weather.WetSurfaces.GlossLimit", 300, F32),
    field("Weather.WetSurfaces.VFXSplashRange", 304, F32),
    field("Weather.WetSurfaces.VFXSplashRate", 308, F32),
    field("Ocean.ReflectionMap", 312, AssetId),
    field("Ocean.Material", 320, AssetId),
    field("Ocean.DistanceFactor", 328, F32),
    field("Ocean.FoamDissipation", 332, F32),
    field("Ocean.FoamThreshold", 336, F32),
    field("Ocean.FoamAmount", 340, F32),
    field("Ocean.FoamColor", 344, Vec3),
    field("Ocean.WaveAmplitude", 356, F32),
    field("Ocean.ChopScale", 360, F32),
    field("Ocean.WindSpeed", 364, F32),
    field("Ocean.TimeScale", 368, F32),
    field("Ocean.Darkening", 372, F32),
    field("Ocean.Depth", 376, F32),
    field("Ocean.Type", 380, U32),
    field("Ocean.AudioMaterialHash", 384, U32),
    field("Ocean.AVMaterialHash", 388, U32),
    field("Ocean.Color", 392, Vec3),
    field("Ocean.WindIndependence", 404, F32),
    field("Ocean.OverrideWindDir", 408, U8),
    field("Ocean.Normalz", 412, F32),
    field("Ocean.FoamAmp", 416, F32),
    field("Ocean.FoamMin", 420, F32),
    field("Ocean.FoamMax", 424, F32),
    field("Ocean.FoamBias", 428, F32),
    field("Ocean.FoamSizzle", 432, F32),
    field("Ocean.FoamPower", 436, F32),
    field("Ocean.WaveElongate", 440, F32),
    field("Ocean.Cascade0", 444, F32),
    field("Ocean.Cascade1", 448, F32),
    field("Ocean.Cascade2", 452, F32),
    field("Ocean.Cascade3", 456, F32),
    field("Ocean.Tile0", 460, F32),
    field("Ocean.Tile1", 464, F32),
    field("Ocean.Tile2", 468, F32),
    field("Ocean.Tile3", 472, F32),
    field("Ocean.Wave0", 476, F32),
    field("Ocean.Wave1", 480, F32),
    field("Ocean.Wave2", 484, F32),
    field("Ocean.Wave3", 488, F32),
    field("Ocean.FoamEmit", 492, F32),
    field("Ocean.FoamFade", 496, F32),
    field("Ocean.CausticsIntensity", 500, F32),
    field("Ocean.CausticsDepthBias", 504, F32),
    field("Weather.Particles.Texture", 512, AssetRef),
    field("Weather.Particles.Color", 536, Vec3),
    field("Weather.Particles.Alpha", 548, F32),
    field("Weather.Particles.NearFadeDistance", 552, F32),
    field("Weather.Particles.MaxDrawDistance", 556, F32),
    field("Weather.Particles.Turbulence", 560, F32),
    field("Weather.Particles.WindInfluence", 564, F32),
    field("Weather.Particles.Speed", 568, F32),
    field("Weather.Particles.Density", 572, F32),
    field("Weather.Particles.Size", 576, F32),
    field("Weather.Particles.ExposureDuration", 580, F32),
    field("Weather.Particles.MotionStretchMax", 584, F32),
    field("Weather.Particles.MotionStretchMaxFar", 588, F32),
    field("Weather.Particles.RainBloomInfluence", 592, F32),
    field("Weather.Wind.Intensity", 600, F32),
    field("Weather.Wind.Azimuth", 604, F32),
    field("Weather.Wind.WindGustsIntensity.Min", 608, F32),
    field("Weather.Wind.WindGustsIntensity.Max", 612, F32),
    field("Weather.Wind.WindGustsFrequency.Min", 616, F32),
    field("Weather.Wind.WindGustsFrequency.Max", 620, F32),
    field("Weather.Wind.WindGustsDuration.Min", 624, F32),
    field("Weather.Wind.WindGustsDuration.Max", 628, F32),
    field("ToneMapSettings.Enabled", 632, U8),
    field("ToneMapSettings.AdaptationAnchor", 636, F32),
    field("ToneMapSettings.AdaptationRange", 640, F32),
    field("ToneMapSettings.AdaptationBias", 644, F32),
    field("ToneMapSettings.AutoAdjustTime", 648, F32),
    field("Weather.WeatherConstant", 652, F32),
    field("BloomSettings.Intensity", 656, F32),
    field("BloomSettings.Threshold", 660, F32),
    field("BloomSettings.GaussianStrength0", 664, F32),
    field("BloomSettings.GaussianStrength1", 668, F32),
    field("BloomSettings.GaussianStrength2", 672, F32),
    field("BloomSettings.GaussianStrength3", 676, F32),
    field("BloomSettings.GaussianStrength4", 680, F32),
    field("BloomSettings.BloomDirtiness", 684, F32),
    field("BloomSettings.BloomDirtinessAsset", 688, AssetRef),
    field("BloomSettings.LensFlareLumMin", 712, F32),
    field("BloomSettings.LensFlareLumMax", 716, F32),
    field("BloomSettings.LensFlareLumIntensity", 720, F32),
    field("BloomSettings.LensFlareGhosts", 724, F32),
    field("BloomSettings.LensFlareFallOff", 728, F32),
    field("BloomSettings.LensFlareIntensity", 732, F32),
    field("BloomSettings.LensFlareDistortion", 736, F32),
    field("BloomSettings.LensFlareHaloRadius", 740, F32),
    field("BloomSettings.LensFlareHaloIntensity", 744, F32),
    field("BloomSettings.LensFlareGhostDispersal", 748, F32),
    field("BloomSettings.AnamorphicLensFlareIntensity", 752, F32),
    field("BloomSettings.AnamorphicLensFlareValueThreshold", 756, F32),
    field("BloomSettings.AnamorphicLensFlareSaturationThreshold", 760, F32),
    field("ColorCorrectionSettings.SourcePath", 768, AssetRef),
    field("VignetteSettings.Intensity", 792, F32),
    field("VignetteSettings.CenterClear", 796, F32),
    field("ChromaticAbSettings.InnerRadius", 800, F32),
    field("ChromaticAbSettings.OuterRadius", 804, F32),
    field("ChromaticAbSettings.DisplacementInPixels", 808, F32),
    field("ChromaticAbSettings.BlurInPixels", 812, F32),
    field("ProjectCustomData.Value", 816, Vec4),
    field("AOSettings.OcclusionStrength", 832, F32),
    field("AOSettings.RadiusInMeters", 836, F32),
    field("AOSettings.DistanceStrength", 840, F32),
    field("AOSettings.DistanceInMeters", 844, F32),
    field("AOSettings.SunlightFactor", 848, F32),
    field("AOSettings.LocalLightFactor", 852, F32),
    field("AOSettings.SkinUnshadowedFactor", 856, F32),
    field("AOSettings.SkinShadowedFactor", 860, F32),
    field("AOSettings.AmbientShadowDrawDist", 864, F32),
    field("AOSettings.AmbientShadowIntensity", 868, F32),
    field("AASettings.TemporalBlendStrength", 872, F32),
    field("AASettings.TemporalSharpenStrength", 876, F32),
    field("SSRSettings.RayTracingDistance", 880, F32),
    field("SSRSettings.Strength", 884, F32),
    field("FogSettings.Color", 892, Vec3),
    field("FogSettings.LuminanceScale", 904, F32),
    field("FogSettings.KeyLightInfluence", 908, F32),
    field("FogSettings.NearRadius", 912, F32),
    field("FogSettings.Height0", 916, F32),
    field("FogSettings.Height1", 920, F32),
    field("FogSettings.Height2", 924, F32),
    field("FogSettings.Height3", 928, F32),
    field("FogSettings.Height4", 932, F32),
    field("FogSettings.Opacity0", 936, F32),
    field("FogSettings.Opacity1", 940, F32),
    field("FogSettings.Opacity2", 944, F32),
    field("FogSettings.Opacity3", 948, F32),
    field("FogSettings.Opacity4", 952, F32),
    field("FogSettings.RemapStrength", 956, F32),
    field("FogSettings.RemapKeyOpacity", 960, F32),
    field("VolumetricFogSettings.Color", 964, Vec3),
    field("VolumetricFogSettings.Opacity", 976, F32),
    field("VolumetricFogSettings.BottomHeight", 980, F32),
    field("VolumetricFogSettings.TopHeight", 984, F32),
    field("VolumetricFogSettings.NearDistance", 988, F32),
    field("VolumetricFogSettings.FarDistance", 992, F32),
    field("VolumetricFogSettings.SunLightScale", 996, F32),
    field("VolumetricFogSettings.LightsScale", 1000, F32),
    field("VolumetricFogSettings.GIScale", 1004, F32),
    field("VolumetricFogSettings.NoiseVSpeed", 1008, F32),
    field("VolumetricFogSettings.NoiseSpeed", 1012, F32),
    field("VolumetricFogSettings.NoiseScale", 1016, F32),
    field("FogSettings.ColorMapDepthRange", 1024, F32),
    field("FogSettings.ColorMapDepthScale", 1028, F32),
    field("FogSettings.ColorMapAsset", 1032, AssetRef),
    field("FogSettings.AlphaMapAsset", 1056, AssetRef),
    field("MotionBlurSettings.ExposureDuration", 1080, F32),
    field("DepthOfFieldSettings.NearFocusDistance", 1088, F32),
    field("DepthOfFieldSettings.NearApertureScale", 1092, F32),
    field("DepthOfFieldSettings.FocusDistance", 1096, F32),
    field("DepthOfFieldSettings.ApertureScale", 1100, F32),
    field("FilmGrainSettings.Size", 1104, F32),
    field("FilmGrainSettings.Strength", 1108, F32),
    field("FilmGrainSettings.SizeAt4K", 1112, F32),
    field("FilmGrainSettings.StrengthAt4K", 1116, F32),
    field("FilmGrainSettings.NoiseTexture", 1120, AssetRef),
    field("ScatteringSettings.RayleighDensity", 1144, F32),
    field("ScatteringSettings.MieDensity", 1148, F32),
    field("ScatteringSettings.MieAlbedo", 1152, Vec3),
    field("LightShaftsSettings.Range", 1164, F32),
    field("LightShaftsSettings.Weight", 1168, F32),
    field("LightShaftsSettings.ConeAngle", 1172, F32),
    field("LightShaftsSettings.SortDistance", 1176, F32),
    field("LightShaftsSettings.Color", 1180, Vec3),
    field("ClipSettings.Near", 1192, F32),
    field("ClipSettings.Far", 1196, F32),
    field("VolumetricClouds.Layer.EnabledRotation", 1200, U8),
    field("VolumetricClouds.Layer.CloudsLayerStart", 1204, F32),
    field("VolumetricClouds.Layer.LayerThickness", 1208, F32),
    field("VolumetricClouds.Layer.BaseTile", 1212, F32),
    field("VolumetricClouds.Layer.DetailTile", 1216, F32),
    field("VolumetricClouds.Layer.DetailStrength", 1220, F32),
    field("VolumetricClouds.Layer.CurlTile", 1224, F32),
    field("VolumetricClouds.Layer.CurlStrength", 1228, F32),
    field("VolumetricClouds.Layer.CloudTopOffset", 1232, F32),
    field("VolumetricClouds.Layer.CloudSize", 1236, F32),
    field("VolumetricClouds.Layer.CloudDensity", 1240, F32),
    field("VolumetricClouds.Layer.CloudCoverageModifier", 1244, F32),
    field("VolumetricClouds.Layer.CloudTypeModifier", 1248, F32),
    field("VolumetricClouds.Layer.AnvilBias", 1252, F32),
    field("VolumetricClouds.Layer.WeatherTexSize", 1256, F32),
    field("VolumetricClouds.Layer.WeatherTexOffsetAzimuth", 1260, F32),
    field("VolumetricClouds.Layer.WeatherTexOffsetDistance", 1264, F32),
    field("VolumetricClouds.Layer.WindAzimuth", 1268, F32),
    field("VolumetricClouds.Layer.WindIntensity", 1272, F32),
    field("VolumetricClouds.Layer.RotationPivotAzimuth", 1276, F32),
    field("VolumetricClouds.Layer.RotationPivotDistance", 1280, F32),
    field("VolumetricClouds.Layer.RotationIntensity", 1284, F32),
    field("VolumetricClouds.Layer.RisingVaporIntensity", 1288, F32),
    field("VolumetricClouds.Layer.NoiseFlowAzimuth", 1292, F32),
    field("VolumetricClouds.Layer.NoiseFlowIntensity", 1296, F32),
    field("VolumetricClouds.2DLayer.EnabledRotation", 1312, U8),
    field("VolumetricClouds.2DLayer.CloudsLayerStart", 1316, F32),
    field("VolumetricClouds.2DLayer.Enabled", 1320, U8),
    field("VolumetricClouds.2DLayer.BaseTile", 1324, F32),
    field("VolumetricClouds.2DLayer.DetailTile", 1328, F32),
    field("VolumetricClouds.2DLayer.DetailStrength", 1332, F32),
    field("VolumetricClouds.2DLayer.CurlTile", 1336, F32),
    field("VolumetricClouds.2DLayer.CurlStrength", 1340, F32),
    field("VolumetricClouds.2DLayer.CloudTopOffset", 1344, F32),
    field("VolumetricClouds.2DLayer.CloudSize", 1348, F32),
    field("VolumetricClouds.2DLayer.CloudDensity", 1352, F32),
    field("VolumetricClouds.2DLayer.CloudCoverageModifier", 1356, F32),
    field("VolumetricClouds.2DLayer.CloudTypeModifier", 1360, F32),
    field("VolumetricClouds.2DLayer.AnvilBias", 1364, F32),
    field("VolumetricClouds.2DLayer.WeatherTexSize", 1368, F32),
    field("VolumetricClouds.2DLayer.WeatherTexOffsetAzimuth", 1372, F32),
    field("VolumetricClouds.2DLayer.WeatherTexOffsetDistance", 1376, F32),
    field("VolumetricClouds.2DLayer.WindAzimuth", 1380, F32),
    field("VolumetricClouds.2DLayer.WindIntensity", 1384, F32),
    field("VolumetricClouds.2DLayer.RotationPivotAzimuth", 1388, F32),
    field("VolumetricClouds.2DLayer.RotationPivotDistance", 1392, F32),
    field("VolumetricClouds.2DLayer.RotationIntensity", 1396, F32),
    field("VolumetricClouds.2DLayer.RisingVaporIntensity", 1400, F32),
    field("VolumetricClouds.2DLayer.NoiseFlowAzimuth", 1404, F32),
    field("VolumetricClouds.2DLayer.NoiseFlowIntensity", 1408, F32),
    field("VolumetricClouds.CurlNoiseTexture", 1424, AssetRef),
    field("VolumetricClouds.WeatherMap", 1448, AssetRef),
    field("VolumetricClouds.HighFrequencyNoiseTex", 1472, AssetRef),
    field("VolumetricClouds.LowFrequencyNoiseTex", 1496, AssetRef),
    field("VolumetricClouds.BackgroundBlendCubemap", 1520, AssetRef),
    field("VolumetricClouds.CustomColor", 1544, Vec3),
    field("VolumetricClouds.Enabled", 1556, U8),
    field("VolumetricClouds.EnabledEdgeBlur", 1557, U8),
    field("VolumetricClouds.EnabledShadow", 1558, U8),
    field("VolumetricClouds.EnabledGodray", 1559, U8),
    field("VolumetricClouds.GodNumSamples", 1560, U32),
    field("VolumetricClouds.Unknown1564", 1564, U32),
    field("VolumetricClouds.Unknown1568", 1568, U32),
    field("VolumetricClouds.Unknown1572", 1572, U32),
    field("VolumetricClouds.MaxSampleDistance", 1576, F32),
    field("VolumetricClouds.CustomColorIntensity", 1580, F32),
    field("VolumetricClouds.CustomColorBlendFactor", 1584, F32),
    field("VolumetricClouds.Contrast", 1588, F32),
    field("VolumetricClouds.TransStepSize", 1592, F32),
    field("VolumetricClouds.BackgroundBlendFactor", 1596, F32),
    field("VolumetricClouds.Precipitation", 1600, F32),
    field("VolumetricClouds.SilverIntensity", 1604, F32),
    field("VolumetricClouds.SilverSpread", 1608, F32),
    field("VolumetricClouds.Eccentricity", 1612, F32),
    field("VolumetricClouds.CloudBrightness", 1616, F32),
    field("VolumetricClouds.FogBlendFactor", 1620, F32),
    field("VolumetricClouds.ShadowBrightness", 1624, F32),
    field("VolumetricClouds.ShadowTiling", 1628, F32),
    field("VolumetricClouds.ShadowSpeed", 1632, F32),
    field("VolumetricClouds.Exposure", 1636, F32),
    field("VolumetricClouds.MaxBrightness", 1640, F32),
    field("VolumetricClouds.Decay", 1644, F32),
    field("VolumetricClouds.Density", 1648, F32),
    field("VolumetricClouds.Weight", 1652, F32),
    field("VolumetricClouds.EarthRadiusScale", 1656, F32),
    field("VolumetricClouds.LocalLight0_Position", 1660, Vec3),
    field("VolumetricClouds.LocalLight0_Color", 1672, Vec3),
    field("VolumetricClouds.LocalLight0_Intensity", 1684, F32),
    field("VolumetricClouds.LocalLight0_AttenRadius", 1688, F32),
    field("VolumetricClouds.LocalLight1_Position", 1692, Vec3),
    field("VolumetricClouds.LocalLight1_Color", 1704, Vec3),
    field("VolumetricClouds.LocalLight1_Intensity", 1716, F32),
    field("VolumetricClouds.LocalLight1_AttenRadius", 1720, F32),
    field("VolumetricClouds.LocalLight2_Position", 1724, Vec3),
    field("VolumetricClouds.LocalLight2_Color", 1736, Vec3),
    field("VolumetricClouds.LocalLight2_Intensity", 1748, F32),
    field("VolumetricClouds.LocalLight2_AttenRadius", 1752, F32),
    field("VolumetricClouds.LocalLight3_Position", 1756, Vec3),
    field("VolumetricClouds.LocalLight3_Color", 1768, Vec3),
    field("VolumetricClouds.LocalLight3_Intensity", 1780, F32),
    field("VolumetricClouds.LocalLight3_AttenRadius", 1784, F32),
];

/// Scalar type an edit at `offset` must use (`float`, `u32` or `u8`); `None` for references,
/// paths and padding, which are not edited directly.
pub fn editable_type(offset: usize) -> Option<&'static str> {
    FIELDS.iter().find_map(|f| {
        let within = |len: usize| offset >= f.offset && offset < f.offset + len && (offset - f.offset) % 4 == 0;
        match f.kind {
            F32 if offset == f.offset => Some("float"),
            Vec3 if within(12) => Some("float"),
            Vec4 if within(16) => Some("float"),
            U32 if offset == f.offset => Some("u32"),
            U8 if offset == f.offset => Some("u8"),
            _ => None,
        }
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fields_are_ordered_and_fit() {
        for pair in FIELDS.windows(2) {
            assert!(pair[0].offset + pair[0].kind.size() <= pair[1].offset, "{} overlaps {}", pair[0].name, pair[1].name);
        }
        let last = FIELDS.last().unwrap();
        assert!(last.offset + last.kind.size() <= HEADER_SIZE);
    }

    #[test]
    fn edit_types() {
        assert_eq!(editable_type(124), Some("float"));
        assert_eq!(editable_type(116), Some("float"));
        assert_eq!(editable_type(148), Some("u8"));
        assert_eq!(editable_type(1557), Some("u8"));
        assert_eq!(editable_type(64), None);
        assert_eq!(editable_type(44), None);
    }
}
